# ---------- Build ----------
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /app

COPY common-db ./common-db
RUN mvn -q -e -DskipTests -f common-db/pom.xml install

COPY feign-clients ./feign-clients
RUN mvn -q -e -DskipTests -f feign-clients/pom.xml install

COPY payment ./payment

RUN mvn -q -e -DskipTests -f payment/pom.xml package

# ---------- Run ----------
FROM eclipse-temurin:21-jre
WORKDIR /app

COPY --from=build /app/payment/target/payment-*.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]
