services:

  generator:
    build:
      context: .
      dockerfile: generator/Dockerfile
    container_name: generator-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/booking
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      SERVICES_REGISTRATOR_URL: http://registrator:8081
    ports:
      - "8080:8080"
    depends_on:
      - registrator

  registrator:
    build:
      context: .
      dockerfile: registrator/Dockerfile
    container_name: registrator-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/booking
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      SERVICES_GENERATOR_URL: http://generator:8080
      SERVICES_PAYMENT_URL: http://payment:8082
    ports:
      - "8081:8081"
    depends_on:
      - payment

  payment:
    build:
      context: .
      dockerfile: payment/Dockerfile
    container_name: payment-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/booking
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      SERVICES_REGISTRATOR_URL: http://registrator:8081
    ports:
      - "8082:8082"
