global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'generator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['generator-service:8080']

  - job_name: 'registrator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['registrator-service:8081']

  - job_name: 'payment'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['payment-service:8082']
