spring:
  application:
    name: generator

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://host.docker.internal:5432/booking
    username: postgres
    password: "postgres"

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/generator-changelog-master.xml
    default_schema: generator_schema
    liquibase-schema: liquibase_history
    database-change-log-table: databasechangelog_generator
    database-change-log-lock-table: databasechangeloglock_generator

server:
  port: 8080

services:
  registrator:
    url: http://registrator:8081/registrator