spring:
  application:
    name: payment

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://host.docker.internal:5432/booking
    username: postgres
    password: "postgres"

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/payment-changelog-master.xml
    default_schema: payment_schema
    liquibase-schema: liquibase_history
    database-change-log-table: databasechangelog_payment
    database-change-log-lock-table: databasechangeloglock_payment

server:
  port: 8082

services:
  registrator:
    url: http://registrator:8081

payment:
  successProbability: 0.7