spring:
  application:
    name: registrator

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://host.docker.internal:5432/booking
    username: postgres
    password: "postgres"

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/registrator-changelog-master.xml
    default_schema: registrator_schema
    liquibase-schema: liquibase_history
    database-change-log-table: databasechangelog_registrator
    database-change-log-lock-table: databasechangeloglock_registrator

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: registrator
      auto-offset-reset: earliest
      properties:
        spring.json.trusted.packages: "*"

server:
  port: 8081

services:
  generator:
    url: http://generator:8080
  payment:
    url: http://payment:8082
